name    'timfreund-kallitheaci'
version '0.1.0'
source' https://github.com/timfreund/puppet-kallitheaci'
author 'timfreund'
license 'GPLv3'
summary 'Configure CI services for the Kallithea project'
description 'Configure CI services for the Kallithea project'
project_page 'https://github.com/timfreund/puppet-kallitheaci'

dependency 'puppetlabs/apt', '>= 1.4.2'
dependency 'puppetlabs/git', '>= 0.0.3'
dependency 'puppetlabs/java', '>= 1.1.1'
dependency 'puppetlabs/stdlib', '>= 3.2.1'
dependency 'rtyler/jenkins', '>= 1.1.0'
